language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgpgme11-dev
install:
  - pip install -r requirements.txt --use-mirrors
script: nosetests
