language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
matrix:
  allow_failures:
    - python: 3.3
    - python: 3.5
    - python: pypy
    - python: pypy3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgpgme11-dev pylint
install:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=. py.test
after_script:
  - pylint zeyple -f colorized -r no
