language: python
dist: xenial # https://github.com/travis-ci/travis-ci/issues/9831
python: # XXX: keep in sync with tox.ini
  - 2.7
  - 3.7
  - pypy
  - pypy3
matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgpgme11-dev pylint
install:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=. py.test
after_script:
  - pylint zeyple -f colorized -r no
